config/routes.rb
Shooring::Application.routes.draw do
  root 'activities#index'

  resources :activities do
    resources :folders do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end

    member do
      get :members
    end
  end

  resources :users
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy", as: "signout"

  resources :folders do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

  resources :files

  namespace :admin do
    root "base#index"

    resources :users do
      resources :permissions

      put "permissions", to: "permissions#set", as: "set_permissions"
    end

    resources :states do
      member do
        get :make_default
      end
    end
  end
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :thing, :polymorphic => true
end

app/controllers/admin/permissions_controller.rb
class Admin::PermissionsController < Admin::BaseController
  before_action :set_user

  def index
    @ability = Ability.new(@user)
    @activities = Activity.all
  end

  def set
    @user.permissions.clear
    params[:permissions].each do |id, permissions|
      activity = Activity.find(id)
      permissions.each do |permission, checked|
        Permission.create!(user: @user,
                           thing: activity,
                           action: permission)
      end
    end
    flash[:notice] = "Permissions updated."
    redirect_to admin_user_permissions_path(@user)
  end


  private
    def set_user
      @user = User.find(params[:user_id])
    end

end

app/helpers/admin/permissions_helper.rb
module Admin::PermissionsHelper
  def permissions
    {
      "view" => "View",
      "create folders" => "Create Folders",
      "edit folders"   => "Edit Folders",
      "delete folders" => "Delete Folders",
      "change states" => "Change States"
    }
  end
end

app/views/admin/permissions/index.html.erb
<h2>Permissions for <%= @user.email %></h2>
<%= form_tag admin_user_set_permissions_path, :method => :put do %>
  <table id='permissions' cellspacing='0'>
   <thead>
    <th>Activity</th>
    <% permissions.each do |name, text| %>
      <th><%= text %></th>
    <% end %>
   </thead>
   <tbody>
    <% @activities.each do |activity| %>
      <tr class='<%= cycle("odd", "even") %>'
           id='activity_<%= activity.id %>'>
       <td><%= activity.name %></td>
       <% permissions.each do |name, text| %>
         <td>
          <%= check_box_tag "permissions[#{activity.id}][#{name}]", 
              1,
              @ability.can?(name.to_sym, activity) %>
         </td>
       <% end %>
      </tr>
    <% end %>
   </tbody>
  </table>
  <%= submit_tag "Update" %>
<% end %>