config/routes.rb
Shooring::Application.routes.draw do
  root 'activities#index'

  resources :activities do
    resources :folders do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end

    member do
      get :members
    end
  end

  resources :users
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy", as: "signout"

  resources :folders do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

  resources :files

  namespace :admin do
    root "base#index"

    resources :users do
      resources :permissions

      put "permissions", to: "permissions#set", as: "set_permissions"
    end

    resources :states do
      member do
        get :make_default
      end
    end
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  validates :name, presence: true

  has_many :folders, dependent: :delete_all #dependent: :nullify
  has_many :permissions, as: :thing

  scope :viewable_by, ->(user) do
    joins(:permissions).where(permissions: { action: "view",
                                             user_id: user.id })
  end

  scope :for, ->(user) do
    user.admin? ? Activity.all : Activity.viewable_by(user)
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authorize_admin!, except: [:index, :show]
  before_action :require_signin!, only: [:index, :show]
  before_action :set_activity, only: [:show, :edit, :update, :destroy, :members]

  def index
    @activities = Activity.for(current_user)
  end

  def show
    @folders = @activity.folders
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      flash[:notice] = "Activity has been created."
      redirect_to @activity
    else
      flash[:alert] = "Activity has not been created."
      render "new"
    end
  end

  def edit
  end

  def update
    if @activity.update(activity_params)
      flash[:notice] = "Activity has been updated."
      redirect_to @activity
    else
      flash[:alert] = "Activity has not been updated."
      render "edit"
    end
  end

  def destroy
    @activity.destroy

    flash[:notice] = "Activity has been deleted."
    redirect_to activities_path
  end

  def members
    @users = User.for(@activity)
  end

  private

    def activity_params
      params.require(:activity).permit(:name, :description)
    end

    def set_activity
      @activity = Activity.for(current_user).find(params[:id])
    rescue ActiveRecord::RecordNotFound
        flash[:alert] = "The activity you were looking for could not be found."
        redirect_to activities_path
    end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
<% if @activity.errors.any? %>
 <div id="error_explanation" >
 <h2><%= pluralize(@activity.errors.count, "error") %>
    prohibited this activity from being saved:</h2>

   <ul>
    <% @activity.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
   </ul>
  </div>
<% end %>

 <p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
 </p>

 <p>
  <%= f.label :description %><br />
  <%= f.text_field :description %>
 </p>
 <%= f.submit %>
<% end %>

app/views/activities/edit.html.erb
<h2>Edit Project</h2>

<%= render "form" %>

app/views/activities/index.html.erb
<% admins_only do %>
 <%= link_to 'New Activity', new_activity_path %>
<% end %>

<h2>Activities</h2>
<ul>
 <% @activities.each do |activity| %>
  <li><%= link_to activity.name, activity %></li>
 <% end %>
</ul>

app/views/activities/members.html.erb
<h2>Members <%= @activity.name %></h2>
<% @users.each do |user| %>
 <li>
  <%= user.name %>
 </li>
<% end %>

app/views/activities/new.html.erb
<h2>New Activity</h2>

<%= render "form" %>

app/views/activities/show.html.erb
<%= title(@activity.name, "Activities") %>

<h2><%= @activity.name %></h2>

<%= form_tag search_activity_folders_path(@activity),
             method: :get do %>
  <%= label_tag "search" %>
  <%= text_field_tag "search", params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<ul id='folders'>
 <% @folders.each do |folder| %>
  <li>
   <%= render folder.state if folder.state %>
   #<%= folder.id %> - <%= link_to folder.name, [@activity, folder] %>
  </li>
 <% end %>
</ul>

<% admins_only do %>
 <%= link_to "Edit Activity", edit_activity_path(@activity) %>
 <%= link_to "Delete Activity", activity_path(@activity),
                                method: :delete,
                                data: {confirm: "Are you sure you want to delete this activity?" } %>
<% end %>

<% authorized?(:"create folders", @activity) do %>
  <%= link_to "New Folder", new_activity_folder_path(@activity) %>
<% end %>

<%= link_to "Members", members_activity_path(@activity) %>